name = "MPChat"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]‌:ml-citation{ref="3" data="citationList"}
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://mpchat.io" # 替换为实际域名
