name = "mpchat-landingpage"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 配置
pages_build_output_dir = "out"

# 生产环境变量
[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://mpchat.io"

# 预览环境变量
[env.preview.vars]
NEXT_PUBLIC_SITE_URL = "https://preview.mpchat.io"
